### ISSUE TITLE
Rails seed data for listings

### ISSUE THREAD

**Issue by howdoicomputer** [codeforsanjose/findahome#7]
This is *super* important for development and is a fairly high priority. Listings are currently populated via crawling and that's not really sustainable for local development.

**Comment by howdoicomputer** [comment]
@ychoy http://edgeguides.rubyonrails.org/active_record_migrations.html#migrations-and-seed-data

Take a look https://github.com/codeforsanjose/findahome/blob/development/db/schema.rb

Data records don't need to be complete (listings probably don't need to be seeded with a full set of attributes) but at least include some fake addresses.

I think a starting count of five would be good.

Later, when I work on #20, I'll add in lat/lng coordinates.

**Comment by ychoy** [comment]
Added 5 listings with data from Social Service's San Jose listings with attributes including rent, address, lat/long, accepts section 8?.
